[package]
name = "ppm"
version = "0.1.0"
authors = ["Daniel Jay Haskin <djhaskin987@gmail.com>"]
edition = "2018"

[dependencies]
clap = "2"
path-clean = "0.1"
rusqlite = "0.19"
stderrlog = "0.4"
log = "0.4"
